include Make.defines

PROGS =	 client server 

OPTIONS = -DUNIX  -DANSI


COBJECTS =	DieWithMessage.o AddressUtility.o
CSOURCES =	DieWithMessage.c  AddressUtility.c

CPLUSOBJECTS = 

COMMONSOURCES =

CPLUSSOURCES =

all:	${PROGS}


client:		UDPEchoClient.o $(CPLUSOBJECTS) $(COBJECTS) $(LIBS) $(COMMONSOURCES) $(SOURCES)
		${CC} ${LINKOPTIONS}  $@ UDPEchoClient.o $(CPLUSOBJECTS) $(COBJECTS) $(LIBS) $(LINKFLAGS)


server:		UDPEchoServer.o $(CPLUSOBJECTS) $(COBJECTS)
		${CC} ${LINKOPTIONS} $@ UDPEchoServer.o $(CPLUSOBJECTS) $(COBJECTS) $(LIBS) $(LINKFLAGS)



.cc.o:	$(HEADERS)
	$(CPLUS) $(CPLUSFLAGS) $(OPTIONS) $<

.c.o:	$(HEADERS)
	$(CC) $(CFLAGS) $(OPTIONS) $<



backup:
	rm -f newUDPEcho.tar
	rm -f newUDPEcho.tar.gz
	tar -cf newUDPEcho.tar *
	gzip -f newUDPEcho.tar

clean:
		rm -f ${PROGS} ${CLEANFILES}

depend:
		makedepend UDPEchoClient-Timeout.c UDPEchoServer-SIGIO.c $(CFLAGS) $(HEADERS) $(SOURCES) $(COMMONSOURCES) $(CSOURCES)
#		mkdep $(CFLAGS) $(HEADERS) $(SOURCES) $(COMMONSOURCES) $(CSOURCES)

# DO NOT DELETE

UDPEchoClient.o: /usr/include/stdio.h /usr/include/features.h
UDPEchoClient.o: /usr/include/libio.h /usr/include/_G_config.h
UDPEchoClient.o: /usr/include/wchar.h /usr/include/xlocale.h
UDPEchoClient.o: /usr/include/stdlib.h /usr/include/alloca.h
UDPEchoClient.o: /usr/include/string.h /usr/include/unistd.h
UDPEchoClient.o: /usr/include/getopt.h /usr/include/ctype.h
UDPEchoClient.o: /usr/include/endian.h /usr/include/netdb.h
UDPEchoClient.o: /usr/include/netinet/in.h /usr/include/stdint.h
UDPEchoClient.o: /usr/include/rpc/netdb.h Practical.h
UDPEchoServer.o: /usr/include/stdlib.h /usr/include/features.h
UDPEchoServer.o: /usr/include/alloca.h /usr/include/string.h
UDPEchoServer.o: /usr/include/xlocale.h /usr/include/netdb.h
UDPEchoServer.o: /usr/include/netinet/in.h /usr/include/stdint.h
UDPEchoServer.o: /usr/include/endian.h /usr/include/rpc/netdb.h Practical.h
UDPEchoServer.o: /usr/include/stdio.h /usr/include/libio.h
UDPEchoServer.o: /usr/include/_G_config.h /usr/include/wchar.h
DieWithMessage.o: /usr/include/stdio.h /usr/include/features.h
DieWithMessage.o: /usr/include/libio.h /usr/include/_G_config.h
DieWithMessage.o: /usr/include/wchar.h /usr/include/xlocale.h
DieWithMessage.o: /usr/include/stdlib.h /usr/include/alloca.h
AddressUtility.o: /usr/include/stdio.h /usr/include/features.h
AddressUtility.o: /usr/include/libio.h /usr/include/_G_config.h
AddressUtility.o: /usr/include/wchar.h /usr/include/xlocale.h
AddressUtility.o: /usr/include/string.h /usr/include/arpa/inet.h
AddressUtility.o: /usr/include/netinet/in.h /usr/include/stdint.h
AddressUtility.o: /usr/include/endian.h
